language: node_js

node_js:
  - stable

cache:
  - node_modules

script:
  - npm test
  - npm run build

deploy:
  provider: heroku
  api_key: b7fa582d-233c-4ef1-945b-ca2eb67727d4
  app: flick-staging
